services:
  mysql:
    image: 'mysql:8.0.35'
    environment:
      - 'MYSQL_DATABASE=${DATABASE_NAME}'
      - 'MYSQL_PASSWORD=${DATABASE_ROOT_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}'
      - 'MYSQL_USER=${DATABASE_USER}'
    ports:
      - '3306:3306'
